plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
}

allprojects {
    group = 'io.github.damyeong'
    version = '0.0.1-SNAPSHOT'
}

subprojects {
    apply plugin: 'java'
    repositories {
        mavenCentral()
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

ext {
    lombokVersion = '1.18.32'
}
